### PR TITLE
Fixes for ovms

### PR DESCRIPTION
**Pull request by jerinmax**
1. Updated the inference URL in objectGraphTopology.json to make OpenVINO as default inference endpoint.
2. Updated the README with instructions to modify inference endpoint .

### CODE REVIEW

**Comment by gadamilan** [comment]
@sseiber - Can you please review this and let me know if this is good to merge?

**Review by sseiber — CHANGES_REQUESTED** [review]
@jerinmax @gadamilan The result of this would make the "default" endpoint for the object detection graph be the OpenVINO endpoint. So this would move the potential user confusion from lva implementations with OpenVINO to lva implementations with Yolov3.

It's worth considering whether we should remove the default and document to users to include the "inferencingUrl" parameter in the `./setup/objectGraphInstance.json` file.

**Comment by jerinmax** [comment]
> @jerinmax @gadamilan The result of this would make the "default" endpoint for the object detection graph be the OpenVINO endpoint. So this would move the potential user confusion from lva implementations with OpenVINO to lva implementations with Yolov3.
> 
> It's worth considering whether we should remove the default and document to users to include the "inferencingUrl" parameter in the `./setup/objectGraphInstance.json` file.

**Comment by jerinmax** [comment]
> @jerinmax @gadamilan The result of this would make the "default" endpoint for the object detection graph be the OpenVINO endpoint. So this would move the potential user confusion from lva implementations with OpenVINO to lva implementations with Yolov3.
> 
> It's worth considering whether we should remove the default and document to users to include the "inferencingUrl" parameter in the `./setup/objectGraphInstance.json` file.

@sseiber  Updated objectGraphTopology.json, objectGraphInstance.json and README as per your suggestion. Kindly review and let me know if you have any questions

**Comment by sseiber** [comment]
@jerinmax @gadamilan This looks good. A new container will need to be built in order to use this change.

**Comment by gadamilan** [comment]
@sseiber - So wait for merge until the new container is built?

**Comment by sseiber** [comment]
@jerinmax this looks good. @gadamilan this can be merged - they will create instructions to build a new container when using OVMS endpoints.

**Comment by jerinmax** [comment]
> @jerinmax this looks good. @gadamilan this can be merged - they will create instructions to build a new container when using OVMS endpoints.

@sseiber Anything pending from my side that is blocking the merge ?  May i know where should i add instructions to build container for OVMS?

**Comment by gadamilan** [comment]
@jerinmax - This is merged now

**Pull request merged**
