### PR TITLE
Add Eflow Support

### PR DESCRIPTION
**Pull request by naiteeks**

### CODE REVIEW

**Comment by naiteeks** [comment]
@bennage  - can you please review these code changes. They support changes to support EFLOW with LVA
@gadamilan  - for awareness.

**Comment by bennage** [comment]
Edits submitted in a PR

**Review by bennage — COMMENTED** [review]
We could make UX improvement and even collapse some logic.
However, since we are replacing the script the changes are low value and the script will perform as needed.

**Review by bennage — APPROVED** [review]

**Comment by avkewalr-msft** [comment]
@naiteeks - can we merge these in ? It looks like Christopher has tested and signed off?

You and I had already tested this and signed off and if no major changes have happened since then, this should be good to go from my end.

**Pull request merged**
