### PR TITLE
Lva deepstream

### PR DESCRIPTION
**Pull request by nicolasbotto**

### CODE REVIEW

**Comment by naiteeks** [comment]
@avkewalr-msft  - is this good to merge?

**Comment by avkewalr-msft** [comment]
@naiteeks - have not received go ahead from Nvidia. Nico and I had a meeting this am with them and have asked Nico to track.

@nicolasbotto

**Comment by gadamilan** [comment]
@naiteeks - What do we need to do with this PR?

**Comment by avkewalr-msft** [comment]
@naiteeks , @gadamilan  - This PR is good to merge. We have tested with latest DS 5.1.

**Pull request merged**
